### ISSUE TITLE
create ts-bff-template

### ISSUE THREAD

**Issue by TuranC** [VilnaCRM-Org/ts-bff-template#1]
As a developer, I need to be able easily to create and set up new BFF for the VilnaCRM project

### Technical requirements

- [ ] Node.js 21
- [ ] Nest.js 10
- [ ] DynamoDB
- [ ] [TypeDORM](https://github.com/typedorm/typedorm)
- [ ] [S3](https://www.npmjs.com/package/@aws-sdk/client-s3)
- [ ] [GraphQL](https://www.npmjs.com/package/@nestjs/apollo) [Doc Nest.js](https://docs.nestjs.com/graphql/quick-start)
- [ ] [OpenAPI](https://docs.nestjs.com/openapi/introduction)
- [ ] [Oauth](https://www.passportjs.org/packages/passport-oauth2/)
- [ ] add Pnpm

### Tasks

- [ ] create the repository template for BFF-based microservices
- [ ] set up docker for service
- [ ] set up CI checks using Github actions (SonarQube, pnpm audit, unit tests, e2e, fuzz testing, integrations testing, load testing, mutations testing)
- [ ] need to add husky and [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] write for all repositories CONTRIBUTE.md and README.md
- [ ] check that swagger documentation looks good
- [ ] add [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [ ] cover the code with auto-tests

### Backend CI checks

- [ ] [openapi-diff](https://github.com/VilnaCRM-Org/user-service/blob/main/.github/workflows/openapi-diff.yml)
- [ ] eslint, tslint, prettier, markdownlint
- [ ] pnpm audit
- [ ] [Snyk security checker](https://snyk.io/code-checker/typescript/)
- [ ] need to add script for [checking node.js version](https://github.com/VilnaCRM-Org/frontend-ssr-template/blob/main/checkNodeVersion.js)
- [ ] [nest.js testing](https://docs.nestjs.com/fundamentals/testing)
- [ ] [Cucumber.js](https://cucumber.io/docs/installation/javascript/)
- [ ] [Copy paste detector](https://www.npmjs.com/package/jscpd)
- [ ] [autorelease](https://github.com/VilnaCRM-Org/php-service-template/blob/main/.github/workflows/autorelease.yml)
- [ ] codecov
- [ ] k6 load testing
- [ ] CodeScene
- [ ] SonarQube
- [ ] Snyk
- [ ] [docker-bench-security](https://github.com/docker/docker-bench-security)
- [ ] [Github Secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning)
- [ ] [check for API backward compatibility](https://github.com/marketplace/actions/openapi-diff)

### Acceptance criteria

- [ ] the BFF service template implemented and works as GitHub public template
- [ ] all tests passed
